
@Unittest
Feature: Create qa unittest


    Scenario Outline: Scenario Outline name: Create qa by  1 MA 1 SA 1 FA question with 50 options
        Given Launch the application
        # And Click the Add New Button
        # # When Select the SortOrder as "Ascending"
        # And Select the DefaultLanguage as "English"
        # And Select the RequiredLanguage as "Japanese"
        # And Enter the english title as "<Title in English>"
        # And Enter the jp title as "<Title in JP>"
        # And Enter the EN description as "<Description in English>"
        # And Enter the JP description as "<Description in JP>"
        # Then Click on the Save and Continue Button
        # And create question with 50 options as "<Question 1 in English>","<OP 1 in English>","<OP 2 in English>","<OP 3 in English>","<OP 4 in English>","<Question 2 in English>","<SOP 1 in English>","<SOP 2 in English>","<SOP 3 in English>","<SOP 4 in English>","<Question 3 in English>","<Question 1 in JP>","<OP 1 in JP>","<OP 2 in JP>","<OP 3 in JP>","<OP 4 in JP>","<Question 2 in JP>","<SOP 1 in JP>","<SOP 2 in JP>","<SOP 3 in JP>","<SOP 4 in JP>","<Question 3 in JP>"


        # Scenario: Create qa by  10 MA question with 50 options
        #     Given Launch the application
        #     And Click the Add New Button
        #     #When Select the SortOrder as "Ascending"
        #     And Select the DefaultLanguage as "English"
        #     And Select the RequiredLanguage as "Japanese"
        #     And Enter the english title as "Auto5111"
        #     And Enter the EN description as "Auto1"
        #     And Enter the jp title as "Auto 123441"
        #     And Enter the JP description as "Auto 1"


        #     Then Click on the Save and Continue Button
        #     Then create 10 MA question with 50 options


        Examples:
            | Title in English | Title in JP     | Description in English                                                                                                                                                                                                                           | Description in JP                                                                                                                                                                                                                     | Question 1 in English                   | OP 1 in English | OP 2 in English | OP 3 in English     | OP 4 in English   | Question 2 in English                                     | SOP 1 in English | SOP 2 in English | SOP 3 in English | SOP 4 in English | Question 3 in English                        | Question 1 in JP                                   | OP 1 in JP     | OP 2 in JP | OP 3 in JP | OP 4 in JP | Question 2 in JP                                         | SOP 1 in JP | SOP 2 in JP | SOP 3 in JP | SOP 4 in JP | Question 3 in JP                       |
            | Cache Test 1     | Cache Test JP 1 | This survey could explore various aspects of Japanese culture, including traditional customs, festivals, etiquette, and values. It could cover topics such as tea ceremonies, traditional clothing and other cultural practices unique to Japan. | この調査では、伝統的な習慣、祭り、礼儀作法、価値観など、日本文化のさまざまな側面を調査することができます。茶道、伝統衣装（着物/浴衣）、武道（剣道や柔道など）、その他日本特有の文化的実践などのトピックを取り上げることができます。、 | What are some renewable energy sources? | Solar power     | Wind power      | Hydroelectric power | Geothermal energy | Which countries are leading in renewable energy adoption? | Germany          | China            | United States    | Denmark          | What are the benefits of sustainable energy? | 再生可能エネルギー源はどのようなものがありますか？ | 地熱エネルギー | 水力発電   | 風力発電   | 太陽光発電 | 再生可能エネルギーの普及でリードしている国はどこですか？ | デンマーク  | デンマーク  | デンマーク  | デンマーク  | 持続可能なエネルギーの利点は何ですか？ |
# | Cache Test 2     | Cache Test JP 2 | This survey could explore various aspects of Japanese culture, including traditional customs, festivals, etiquette, and values. It could cover topics such as tea ceremonies, traditional clothing and other cultural practices unique to Japan. | この調査では、伝統的な習慣、祭り、礼儀作法、価値観など、日本文化のさまざまな側面を調査することができます。茶道、伝統衣装（着物/浴衣）、武道（剣道や柔道など）、その他日本特有の文化的実践などのトピックを取り上げることができます。、 | What are some renewable energy sources? | Solar power     | Wind power      | Hydroelectric power | Geothermal energy | Which countries are leading in renewable energy adoption? | Germany          | China            | United States    | Denmark          | What are the benefits of sustainable energy? | 再生可能エネルギー源はどのようなものがありますか？ | 地熱エネルギー | 水力発電   | 風力発電   | 太陽光発電 | 再生可能エネルギーの普及でリードしている国はどこですか？ | デンマーク  | デンマーク  | デンマーク  | デンマーク  | 持続可能なエネルギーの利点は何ですか？ |
# | Cache Test 3     | Cache Test JP 3 | This survey could explore various aspects of Japanese culture, including traditional customs, festivals, etiquette, and values. It could cover topics such as tea ceremonies, traditional clothing and other cultural practices unique to Japan. | この調査では、伝統的な習慣、祭り、礼儀作法、価値観など、日本文化のさまざまな側面を調査することができます。茶道、伝統衣装（着物/浴衣）、武道（剣道や柔道など）、その他日本特有の文化的実践などのトピックを取り上げることができます。、 | What are some renewable energy sources? | Solar power     | Wind power      | Hydroelectric power | Geothermal energy | Which countries are leading in renewable energy adoption? | Germany          | China            | United States    | Denmark          | What are the benefits of sustainable energy? | 再生可能エネルギー源はどのようなものがありますか？ | 地熱エネルギー | 水力発電   | 風力発電   | 太陽光発電 | 再生可能エネルギーの普及でリードしている国はどこですか？ | デンマーク  | デンマーク  | デンマーク  | デンマーク  | 持続可能なエネルギーの利点は何ですか？ |
# | Cache Test 4     | Cache Test JP 4 | This survey could explore various aspects of Japanese culture, including traditional customs, festivals, etiquette, and values. It could cover topics such as tea ceremonies, traditional clothing and other cultural practices unique to Japan. | この調査では、伝統的な習慣、祭り、礼儀作法、価値観など、日本文化のさまざまな側面を調査することができます。茶道、伝統衣装（着物/浴衣）、武道（剣道や柔道など）、その他日本特有の文化的実践などのトピックを取り上げることができます。、 | What are some renewable energy sources? | Solar power     | Wind power      | Hydroelectric power | Geothermal energy | Which countries are leading in renewable energy adoption? | Germany          | China            | United States    | Denmark          | What are the benefits of sustainable energy? | 再生可能エネルギー源はどのようなものがありますか？ | 地熱エネルギー | 水力発電   | 風力発電   | 太陽光発電 | 再生可能エネルギーの普及でリードしている国はどこですか？ | デンマーク  | デンマーク  | デンマーク  | デンマーク  | 持続可能なエネルギーの利点は何ですか？ |
# | Cache Test 5     | Cache Test JP 5 | This survey could explore various aspects of Japanese culture, including traditional customs, festivals, etiquette, and values. It could cover topics such as tea ceremonies, traditional clothing and other cultural practices unique to Japan. | この調査では、伝統的な習慣、祭り、礼儀作法、価値観など、日本文化のさまざまな側面を調査することができます。茶道、伝統衣装（着物/浴衣）、武道（剣道や柔道など）、その他日本特有の文化的実践などのトピックを取り上げることができます。、 | What are some renewable energy sources? | Solar power     | Wind power      | Hydroelectric power | Geothermal energy | Which countries are leading in renewable energy adoption? | Germany          | China            | United States    | Denmark          | What are the benefits of sustainable energy? | 再生可能エネルギー源はどのようなものがありますか？ | 地熱エネルギー | 水力発電   | 風力発電   | 太陽光発電 | 再生可能エネルギーの普及でリードしている国はどこですか？ | デンマーク  | デンマーク  | デンマーク  | デンマーク  | 持続可能なエネルギーの利点は何ですか？ |
# | Cache Test 6     | Cache Test JP 6 | This survey could explore various aspects of Japanese culture, including traditional customs, festivals, etiquette, and values. It could cover topics such as tea ceremonies, traditional clothing and other cultural practices unique to Japan. | この調査では、伝統的な習慣、祭り、礼儀作法、価値観など、日本文化のさまざまな側面を調査することができます。茶道、伝統衣装（着物/浴衣）、武道（剣道や柔道など）、その他日本特有の文化的実践などのトピックを取り上げることができます。、 | What are some renewable energy sources? | Solar power     | Wind power      | Hydroelectric power | Geothermal energy | Which countries are leading in renewable energy adoption? | Germany          | China            | United States    | Denmark          | What are the benefits of sustainable energy? | 再生可能エネルギー源はどのようなものがありますか？ | 地熱エネルギー | 水力発電   | 風力発電   | 太陽光発電 | 再生可能エネルギーの普及でリードしている国はどこですか？ | デンマーク  | デンマーク  | デンマーク  | デンマーク  | 持続可能なエネルギーの利点は何ですか？ |
# | Cache Test 7     | Cache Test JP 7 | This survey could explore various aspects of Japanese culture, including traditional customs, festivals, etiquette, and values. It could cover topics such as tea ceremonies, traditional clothing and other cultural practices unique to Japan. | この調査では、伝統的な習慣、祭り、礼儀作法、価値観など、日本文化のさまざまな側面を調査することができます。茶道、伝統衣装（着物/浴衣）、武道（剣道や柔道など）、その他日本特有の文化的実践などのトピックを取り上げることができます。、 | What are some renewable energy sources? | Solar power     | Wind power      | Hydroelectric power | Geothermal energy | Which countries are leading in renewable energy adoption? | Germany          | China            | United States    | Denmark          | What are the benefits of sustainable energy? | 再生可能エネルギー源はどのようなものがありますか？ | 地熱エネルギー | 水力発電   | 風力発電   | 太陽光発電 | 再生可能エネルギーの普及でリードしている国はどこですか？ | デンマーク  | デンマーク  | デンマーク  | デンマーク  | 持続可能なエネルギーの利点は何ですか？ |
# | Cache Test 8     | Cache Test JP 8 | This survey could explore various aspects of Japanese culture, including traditional customs, festivals, etiquette, and values. It could cover topics such as tea ceremonies, traditional clothing and other cultural practices unique to Japan. | この調査では、伝統的な習慣、祭り、礼儀作法、価値観など、日本文化のさまざまな側面を調査することができます。茶道、伝統衣装（着物/浴衣）、武道（剣道や柔道など）、その他日本特有の文化的実践などのトピックを取り上げることができます。、 | What are some renewable energy sources? | Solar power     | Wind power      | Hydroelectric power | Geothermal energy | Which countries are leading in renewable energy adoption? | Germany          | China            | United States    | Denmark          | What are the benefits of sustainable energy? | 再生可能エネルギー源はどのようなものがありますか？ | 地熱エネルギー | 水力発電   | 風力発電   | 太陽光発電 | 再生可能エネルギーの普及でリードしている国はどこですか？ | デンマーク  | デンマーク  | デンマーク  | デンマーク  | 持続可能なエネルギーの利点は何ですか？ |
# | Cache Test 9     | Cache Test JP 9 | This survey could explore various aspects of Japanese culture, including traditional customs, festivals, etiquette, and values. It could cover topics such as tea ceremonies, traditional clothing and other cultural practices unique to Japan. | この調査では、伝統的な習慣、祭り、礼儀作法、価値観など、日本文化のさまざまな側面を調査することができます。茶道、伝統衣装（着物/浴衣）、武道（剣道や柔道など）、その他日本特有の文化的実践などのトピックを取り上げることができます。、 | What are some renewable energy sources? | Solar power     | Wind power      | Hydroelectric power | Geothermal energy | Which countries are leading in renewable energy adoption? | Germany          | China            | United States    | Denmark          | What are the benefits of sustainable energy? | 再生可能エネルギー源はどのようなものがありますか？ | 地熱エネルギー | 水力発電   | 風力発電   | 太陽光発電 | 再生可能エネルギーの普及でリードしている国はどこですか？ | デンマーク  | デンマーク  | デンマーク  | デンマーク  | 持続可能なエネルギーの利点は何ですか？ |



