name: CI-Target HIT
on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: OWASP ZAP Baseline Scan - Target 1
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://bff.paymentgateway.ip-poc.com/bff/v1/gmo-charge'

      - name: Save Scan Report - Target 1
        run: mv zap-baseline-report.html myreport-gmo-$(date +"%Y%m%d%H%M%S").html

      - name: OWASP ZAP Baseline Scan - Target 2
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://bff.paymentgateway.ip-poc.com/bff/v1/jcb-charge'

      - name: Save Scan Report - Target 2
        run: mv zap-baseline-report.html myreport-jcb-$(date +"%Y%m%d%H%M%S").html

      - name: Check for Issues in Scan Reports
        run: |
          # Assuming you have a script to check the report for issues (e.g., using a tool like grep)
          issues_found=false
          for report in myreport*.html; do
            if grep -q 'Vulnerability Found' "$report"; then
              issues_found=true
            fi
          done

          if $issues_found; then
            echo "Security issues found in the scan reports."
            exit 1  # Exit with an error code to stop the workflow
          else
            echo "No security issues found in the scan reports."
          fi

      - name: Publish Scan Reports
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: myreport*.html
