name: CI
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          targets: |
            https://bff.paymentgateway.ip-poc.com/bff/v1/gmo-charge,
            https://bff.paymentgateway.ip-poc.com/bff/v1/jcb-charge,
            https://additional-target-url1,
            https://additional-target-url2
            # Add as many additional target URLs as needed

      - name: Save Scan Reports
        run: |
          # Rename the report files to something unique
          for report in zap-baseline-report-*.html; do
            mv "$report" myreport-"$report"
          done

      - name: Check for Issues in Scan Reports
        run: |
          # Assuming you have a script to check the report for issues (e.g., using a tool like grep)
          issues_found=false
          for report in myreport*.html; do
            if grep -q 'Vulnerability Found' "$report"; then
              issues_found=true
            fi
          done

          if $issues_found; then
            echo "Security issues found in the scan reports."
            exit 1  # Exit with an error code to stop the workflow
          else
            echo "No security issues found in the scan reports."
          fi

      - name: Publish Scan Reports
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: myreport*.html
