name: CI -simng
on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: OWASP ZAP Baseline Scan (Single Target)
        uses: zaproxy/action-baseline@v0.7.0
        with:
          targets: 'https://bff.paymentgateway.ip-poc.com/bff/v1/gmo-charge'

      - name: Save Scan Report
        run: mv zap-baseline-report.html myreport.html

      - name: Check for Issues in Scan Report
        run: |
          if grep -q 'Vulnerability Found' myreport.html; then
            echo "Security issues found in the scan report."
            exit 1  # Exit with an error code to stop the workflow
          else
            echo "No security issues found in the scan report."
          fi

      - name: Publish Scan Report
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-report
          path: myreport.html
