name: CI-2
on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send API Request with POST method
        run: |
          # Define the API endpoint and payload
          API_URL="https://bff.paymentgateway.ip-poc.com/bff/v1/gmo-charge"
          PAYLOAD='{"surveyId":"5d58d4f8-c113-4732-8858-f773507b911e","surveyStatus":5,"process":"survey_status_update"}'
          
          # Send a POST request to the API
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$API_URL"

      - name: OWASP ZAP Scan POST Request
        uses: zaproxy/action-api-scan@v0.5.0
        with:
          target: "$API_URL"
          zap-options: "-X POST -H \"Content-Type: application/json\" -d '$PAYLOAD'"
