name: CI Checker
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: OWASP ZAP Baseline Scan
        # You may pin to the exact commit or the version.
        # uses: zaproxy/action-baseline@7cea08522cd386f6c675776d5e4296aecf61f33b
        uses: zaproxy/action-baseline@v0.7.0
        with:
          # Target URL
          target: "https://bff.paymentgateway.ip-poc.com/bff/v1/gmo-charge"
   
      - uses: actions/checkout@v3

      # Scan the code for security vulnerabilities using ZAP
      - name: Scan for security issues with ZAP
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          zap-version: 2.12.0
          targets: .
          scan-policy: default
          output-format: json
          ascan-report: ZAP_Scan_Report.json

      # Check the ZAP scan results for vulnerabilities
      - name: Check the ZAP scan results
        run: |
          if [[ $(jq '.alerts | length' ZAP_Scan_Report.json) -gt 0 ]]; then
            echo "Security scan failed. Detected security issues."
            exit 1
          fi

          echo "Security scan passed. No issues found."