name: CI
on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://front.questionnaire.ip-poc.com/app/survey'

      - name: Save Scan Report
        run: mv zap-baseline-report.html myreport-$(date +"%Y%m%d%H%M%S").html

      - name: Check for Issues in Scan Report
        run: |
          # Assuming you have a script to check the report for issues
          if grep -q 'Vulnerability Found' myreport*.html; then
            echo "Security issues found in the scan report."
            exit 1  # Exit with an error code to stop the workflow
          else
            echo "No security issues found in the scan report."
          fi

      - name: Publish Scan Report (if no security issues found)
        if: ${{ failure() == false }}
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-report
          path: myreport*.html

      - name: Fail the workflow if security issues found
        if: ${{ failure() }}
        run: |
          echo "Security issues found in the OWASP ZAP Baseline Scan. Code push canceled."
          exit 1
