name: CI
on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: OWASP ZAP Baseline Scan - Target
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://front.questionnaire.ip-poc.com/app/survey'

      - name: Save Target Scan Report
        run: |
          mv zap-baseline-report.html target-report-$(date +"%Y%m%d%H%M%S").html

      - name: OWASP ZAP Full Scan - Code
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: ${{ github.repository }}

      - name: Save Code Scan Report
        run: |
          mv full-scan-report.html code-report-$(date +"%Y%m%d%H%M%S").html

      - name: Check for Issues in Scan Reports
        run: |
          if grep -q 'Vulnerability Found' *.html; then
            echo "Security issues found in the scan reports."
            exit 1  # Exit with an error code to stop the workflow
          else
            echo "No security issues found in the scan reports."
          fi

      - name: Prevent push if workflow fails
        uses: actions/github-script@v5
        with:
          script: |
            const branchProtectionRule = await github.request('GET /repos/{owner}/{repo}/branches/development/protection');
            if (branchProtectionRule.data.required_status_checks.enforcement === 'none') {
              core.setFailed('Please enable branch protection for the development branch.');
              exit 1;
            }
          fail-fast: false
