name: CI
on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up targets
        id: targets
        run: echo "::set-output name=TARGETS::https://front.paymentgateway.ip-poc.com/app/payment-summary,https://front.questionnaire.ip-poc.com/app/survey"

      - name: Split targets
        id: split_targets
        run: echo "::set-output name=SPLIT_TARGETS::$(echo ${{ steps.targets.outputs.TARGETS }} | tr ',' '\n')"

      - name: OWASP ZAP Baseline Scan
        run: |
          for target in ${{ steps.split_targets.outputs.SPLIT_TARGETS }}; do
            echo "Scanning target: $target"
            zap-baseline.py -t $target
            mv zap-baseline-report.html $(echo zap-baseline-report-$target-$(date +"%Y%m%d%H%M%S").html)
          done

      - name: Check for Issues in Scan Reports
        run: |
          if grep -q 'Vulnerability Found' zap-baseline-report-*.html; then
            echo "Security issues found in the scan reports."
            exit 1  # Exit with an error code to stop the workflow
          else
            echo "No security issues found in the scan reports."
          fi

      - name: Prevent push if workflow fails
        uses: actions/github-script@v5
        with:
          script: |
            const branchProtectionRule = await github.request('GET /repos/{owner}/{repo}/branches/development/protection');
            if (branchProtectionRule.data.required_status_checks.enforcement === 'none') {
              core.setFailed('Please enable branch protection for the development branch.');
              exit 1;
            }
          fail-fast: false
