name: CI
on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://front.questionnaire.ip-poc.com/app/survey'

      - name: Save Scan Report
        run: |
          # Rename the report file to something unique
          mv zap-baseline-report.html myreport-$(date +"%Y%m%d%H%M%S").html

      - name: Check for Issues in Scan Report
        uses: actions/github-script@v5
        with:
          script: |
            const report = fs.readFileSync('myreport*.html', 'utf8');
            if (report.includes('Vulnerability Found')) {
              // Security issues found, fail the workflow
              core.setFailed('Security issues found in the OWASP ZAP Baseline Scan.');

              // Prevent the workflow from publishing the code to GitHub
              core.setOutput('allow-publish', false);
            }
          # Disable the `fail-fast` setting, so that the workflow will continue to execute even if this step fails
          fail-fast: false

      - name: Publish Scan Report
        if: ${{ steps.check-for-issues.outputs.allow-publish == true }}
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-report
          path: myreport*.html

      - name: Fail the workflow if security issues found
        if: ${{ steps.check-for-issues.outputs.allow-publish == false }}
        run: |
          echo "Security issues found in the OWASP ZAP Baseline Scan. Code push canceled."
          exit 1